name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name Check out repository
        uses: actions/checkout@v2

      - name Create folder and add test file
        run: |
          mkdir 1
          echo "Тестовый файл" > 1/file.txt

      - name Install 7-Zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name Compress folder using 7zip
        run: 7z a 1.7z 1/

      - name Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "1.0"
          release_name: "Release 1.0"
          files: 1.7z
