name: Create Release

on:
  push:
    branches:
      - main  # Запускаем workflow при пуше в основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directory
        run: |
          mkdir 1
          echo "Hello, World!" > 1/example.txt  # Пример файла для добавления в папку

      - name: Install p7zip
        run: sudo apt-get install p7zip-full

      - name: Create 7z archive
        run: |
          7z a 1.7z 1/*

      - name: Create tag
        id: create_tag
        run: |
          TAG_NAME="v1.0"  # Замените на нужное имя тега
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Upload release asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: 1.7z
